### ISSUE TITLE
Error using sudo: azure-iot-edge-ijohnson.iotedge

### ISSUE THREAD

**Issue by Gearbrylls** [anonymouse64/azure-iot-edge-snap#1]
Hello

Just got my hands on a new Dell IoT Gateway 3002 Device running Ubuntu-Core and trying to setup Azure IoT Edge following your steps.

I got to the last point now and got the following error:

sudo: azure-iot-edge-ijohnson.iotedge: command not found

Im a total newbie working with Linux and never heard of Ubuntu Core before today.

**Comment by anonymouse64** [comment]
Hi, this repository is unfortunately not to be considered stable yet, so your mileage may vary. :-)

That being said, what happens if you try just running `azure-iot-edge-ijohnson.iotedge list` as non-root user?

**Comment by Gearbrylls** [comment]
A module runtime error occurred
        caused by: Could not list modules
        caused by: an error occurred trying to connect: Connection refused (os error 111)


I have installed the "Classic" version to use apt to get Git working, when following your steps I have been inside this environment. Perhaps that might be the mistake I have made?

**Comment by anonymouse64** [comment]
It's fine to build the snap inside a classic environment from the classic snap, but you won't be able to run any snap commands inside that environment, so you'll need to exit the classic environment in order to use the snap.
What commit did you build the snap from? I recently changed it so that the iotedge sockets are 666 so you shouldn't get that `Connection refused` error if you rebuild the snap and try to run the command again.

**Comment by Gearbrylls** [comment]
Trying to run the newest version but now Im getting a 

/snap/azure-iot-edge-snap$ - Run configure hook of "azure-iot-edge-ijohnson" snap if present (run hook "configure": sed: no input files)

**Comment by anonymouse64** [comment]
That issue should be fixed with https://github.com/anonymouse64/azure-iot-edge-snap/commit/1fb9c6a1af6c35d07f287cc07cfea6388d665564

**Comment by Gearbrylls** [comment]
Tried it this morning, got the following error now. 

Running this command:
sudo snap connect azure-iot-edge-ijohnson:docker-cli azure-iot-edge-ijohnson:docker-daemon

Presented me with this error message:
error: snap "azure-iot-edge-ijohnson" has no plug named "docker-cli"

**Comment by Gearbrylls** [comment]
Ignore the above as I see that the docker-cli has been removed. 
When trying to run the sudo azure-iot-edge-ijohnson.iotedge list command it hangs, when running without the list command I get the other commands presented on the screen.

**Comment by anonymouse64** [comment]
What does the log for `iotedged` say?
i.e. run
```bash
journalctl -ef -u snap.azure-iot-edge-ijohnson.iotedged
```
and either include the output here or put it in a pastebin or gist

**Comment by Gearbrylls** [comment]
/etc/systemd/system# journalctl -ef -u snap.azure-iot-edge-ijohnson.iotedged
-- Logs begin at Thu 2019-02-28 14:33:02 UTC. --
Feb 28 15:03:00 4J8TP42 systemd[1]: Stopped Service for snap application azure-iot-edge-ijohnson.iotedged.
Feb 28 15:03:00 4J8TP42 systemd[1]: Started Service for snap application azure-iot-edge-ijohnson.iotedged.
Feb 28 15:03:01 4J8TP42 azure-iot-edge-ijohnson.iotedged[5869]: 2019-02-28T15:03:01Z [INFO] - Starting Azure IoT Edge Security Daemon
Feb 28 15:03:01 4J8TP42 azure-iot-edge-ijohnson.iotedged[5869]: 2019-02-28T15:03:01Z [INFO] - Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
Feb 28 15:03:01 4J8TP42 azure-iot-edge-ijohnson.iotedged[5869]: 2019-02-28T15:03:01Z [INFO] - Using config file: /var/snap/azure-iot-edge-ijohnson/common/etc/iotedge/config.yaml
Feb 28 15:03:02 4J8TP42 azure-iot-edge-ijohnson.iotedged[5869]: 2019-02-28T15:03:02Z [INFO] - Using runtime network id azure-iot-edge
Feb 28 15:03:02 4J8TP42 azure-iot-edge-ijohnson.iotedged[5869]: 2019-02-28T15:03:02Z [INFO] - Initializing the module runtime...
Feb 28 15:03:02 4J8TP42 azure-iot-edge-ijohnson.iotedged[5869]: 2019-02-28T15:03:02Z [INFO] - Initializing module runtime...

**Comment by anonymouse64** [comment]
That's a known issue with the snap, I haven't been able to figure out the issue yet, but if you just restart it with `snap restart azure-iot-edge-ijohnson.iotedged` you should be able to progress

**Comment by Gearbrylls** [comment]
Tried that, now Im stuck with this error: 


root@4J8TP42:/etc/systemd/system# sudo systemctl status snap.azure-iot-edge-ijohnson.iotedged.service
● snap.azure-iot-edge-ijohnson.iotedged.service - Service for snap application azure-iot-edge-ijohnson.iotedged
   Loaded: loaded (/etc/systemd/system/snap.azure-iot-edge-ijohnson.iotedged.service; static; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Thu 2019-02-28 15:17:51 UTC; 72ms ago
  Process: 7292 ExecStart=/usr/bin/snap run azure-iot-edge-ijohnson.iotedged (code=exited, status=1/FAILURE)
 Main PID: 7292 (code=exited, status=1/FAILURE)

Feb 28 15:17:51 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Main process exited, code=exited, status=1/FAILURE
Feb 28 15:17:51 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Unit entered failed state.
Feb 28 15:17:51 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Failed with result 'exit-code'.
Feb 28 15:17:51 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Service hold-off time over, scheduling restart.
Feb 28 15:17:51 4J8TP42 systemd[1]: Stopped Service for snap application azure-iot-edge-ijohnson.iotedged.
Feb 28 15:17:51 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Start request repeated too quickly.
Feb 28 15:17:51 4J8TP42 systemd[1]: Failed to start Service for snap application azure-iot-edge-ijohnson.iotedged.
Feb 28 15:17:51 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Unit entered failed state.
Feb 28 15:17:51 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Failed with result 'start-limit-hit'.

**Comment by Gearbrylls** [comment]
Tried restarting again and now Im progressing :)

**Comment by Gearbrylls** [comment]
root@4J8TP42:/etc/systemd/system# sudo systemctl status snap.azure-iot-edge-ijohnson.iotedged.service
● snap.azure-iot-edge-ijohnson.iotedged.service - Service for snap application azure-iot-edge-ijohnson.iotedged
   Loaded: loaded (/etc/systemd/system/snap.azure-iot-edge-ijohnson.iotedged.service; static; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Thu 2019-02-28 15:24:48 UTC; 2s ago
  Process: 7967 ExecStart=/usr/bin/snap run azure-iot-edge-ijohnson.iotedged (code=exited, status=1/FAILURE)
 Main PID: 7967 (code=exited, status=1/FAILURE)

Feb 28 15:24:48 4J8TP42 azure-iot-edge-ijohnson.iotedged[7967]: 2019-02-28T15:24:48Z [ERR!] -         caused by: Argument is empty or only has whitespac
Feb 28 15:24:48 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Main process exited, code=exited, status=1/FAILURE
Feb 28 15:24:48 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Unit entered failed state.
Feb 28 15:24:48 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Failed with result 'exit-code'.
Feb 28 15:24:48 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Service hold-off time over, scheduling restart.
Feb 28 15:24:48 4J8TP42 systemd[1]: Stopped Service for snap application azure-iot-edge-ijohnson.iotedged.
Feb 28 15:24:48 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Start request repeated too quickly.
Feb 28 15:24:48 4J8TP42 systemd[1]: Failed to start Service for snap application azure-iot-edge-ijohnson.iotedged.
Feb 28 15:24:48 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Unit entered failed state.
Feb 28 15:24:48 4J8TP42 systemd[1]: snap.azure-iot-edge-ijohnson.iotedged.service: Failed with result 'start-limit-hit'.

**Comment by Gearbrylls** [comment]
Was missing the connection string inside config.yaml, thought that was provided by the .cs file created early in the process. After editing the config.yaml file and restarting it started up correctly :)
