### ISSUE TITLE
Failure Installing Snap

### ISSUE THREAD

**Issue by BradleyHalstead** [anonymouse64/azure-iot-edge-snap#2]
Hi Ian,

I tried to install the snap onto a Dell Gateway 3001 and came up with a configure error.

`admin@3PCR902:~$ snap install azure-iot-edge-ijohnson_1.0.6.1_multi.snap  --dangerous
error: cannot perform the following tasks:
- Run configure hook of "azure-iot-edge-ijohnson" snap if present (run hook "configure": sed: no input files)`

I built this snap on another linux box using cleanbuild.

**Comment by anonymouse64** [comment]
This should be fixed with https://github.com/anonymouse64/azure-iot-edge-snap/commit/1fb9c6a1af6c35d07f287cc07cfea6388d665564
