### ISSUE TITLE
Cross compiling snap on x86 for armhf fails with error

### ISSUE THREAD

**Issue by anwar-ahmed-syed** [anonymouse64/azure-iot-edge-snap#3]
I am not sure which forum should I raise this issue here or snapcraft.io, I am trying to cross-compile snap on amd64 ubuntu with armhf tool-chains installed. Crafting fails with a trace back call which is attached here as reference. I am using `snapcraft --target-arch=armhf` which gives following error:

`NotImplementedError: The plugin used by 'tini' does not support cross-compiling to a different target architecture`.

As the template contains **build-on, run-on** primitives, my understanding is that it should compile seemlessly.
[azure-iot-edge-cc-snap-error.txt](https://github.com/anonymouse64/azure-iot-edge-snap/files/3093298/azure-iot-edge-cc-snap-error.txt)

**Comment by anonymouse64** [comment]
Hi, cross-compiling is not currently supported for this snap. The `build-on` and `run-on` specifications merely are there to declare what architectures the snap is supported on, not to implement cross-compilation. 
That being said, it could probably be made to work if someone contributed cross-compiling support to the `cmake` plugin (and possibly also the `make` plugin I'm not sure). You should inquire on [the forum](forum.snapcraft.io) about cross-compilation support for these snapcraft plugins.
